[theme]
primaryColor = "#F57C00"             # Deep Saffron (Indian vibe)
backgroundColor = "#FFFBE6"          # Pale yellow
secondaryBackgroundColor = "#FFE0B2" # Soft orange
textColor = "#4E342E"                # Coffee brown
font = "sans serif"
